//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.18 at 01:47:31 PM EET 
//


package model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An NewObjectFactory allows you to programatically
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class NewObjectFactory {


    /**
     * Create a new NewObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public NewObjectFactory() {
    }

    /**
     * Create an instance of {@link NewBuildConfigurationModel }
     * 
     */
    public NewBuildConfigurationModel createComAmcbridgeJenkinsPluginsModelsBuildConfigurationModel() {
        return new NewBuildConfigurationModel();
    }

    /**
     * Create an instance of {@link NewBuildConfigurationModel.UserWithAccess }
     * 
     */
    public NewBuildConfigurationModel.UserWithAccess createComAmcbridgeJenkinsPluginsModelsBuildConfigurationModelUserWithAccess() {
        return new NewBuildConfigurationModel.UserWithAccess();
    }

    /**
     * Create an instance of {@link NewBuildConfigurationModel.BuildMachineConfiguration }
     * 
     */
    public NewBuildConfigurationModel.BuildMachineConfiguration createComAmcbridgeJenkinsPluginsModelsBuildConfigurationModelBuildMachineConfiguration() {
        return new NewBuildConfigurationModel.BuildMachineConfiguration();
    }

    /**
     * Create an instance of {@link NewBuildConfigurationModel.ProjectToBuild }
     * 
     */
    public NewBuildConfigurationModel.ProjectToBuild createComAmcbridgeJenkinsPluginsModelsBuildConfigurationModelProjectToBuild() {
        return new NewBuildConfigurationModel.ProjectToBuild();
    }

    /**
     * Create an instance of {@link NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel }
     * 
     */
    public NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel createComAmcbridgeJenkinsPluginsModelsBuildConfigurationModelProjectToBuildComAmcbridgeJenkinsPluginsModelsProjectToBuildModel() {
        return new NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel();
    }

    /**
     * Create an instance of {@link NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders }
     * 
     */
    public NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders createComAmcbridgeJenkinsPluginsModelsBuildConfigurationModelProjectToBuildComAmcbridgeJenkinsPluginsModelsProjectToBuildModelBuilders() {
        return new NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders();
    }

    /**
     * Create an instance of {@link NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders.ComAmcbridgeJenkinsPluginsModelsBuilderConfigModel }
     * 
     */
    public NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders.ComAmcbridgeJenkinsPluginsModelsBuilderConfigModel createComAmcbridgeJenkinsPluginsModelsBuildConfigurationModelProjectToBuildComAmcbridgeJenkinsPluginsModelsProjectToBuildModelBuildersComAmcbridgeJenkinsPluginsModelsBuilderConfigModel() {
        return new NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders.ComAmcbridgeJenkinsPluginsModelsBuilderConfigModel();
    }

    /**
     * Create an instance of {@link NewBuildConfigurationModel.UserWithAccess.ComAmcbridgeJenkinsPluginsModelsUserAccessModel }
     * 
     */
    public NewBuildConfigurationModel.UserWithAccess.ComAmcbridgeJenkinsPluginsModelsUserAccessModel createComAmcbridgeJenkinsPluginsModelsBuildConfigurationModelUserWithAccessComAmcbridgeJenkinsPluginsModelsUserAccessModel() {
        return new NewBuildConfigurationModel.UserWithAccess.ComAmcbridgeJenkinsPluginsModelsUserAccessModel();
    }

    /**
     * Create an instance of {@link NewBuildConfigurationModel.BuildMachineConfiguration.Entry }
     * 
     */
    public NewBuildConfigurationModel.BuildMachineConfiguration.Entry createComAmcbridgeJenkinsPluginsModelsBuildConfigurationModelBuildMachineConfigurationEntry() {
        return new NewBuildConfigurationModel.BuildMachineConfiguration.Entry();
    }

    /**
     * Create an instance of {@link NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Artifacts }
     * 
     */
    public NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Artifacts createComAmcbridgeJenkinsPluginsModelsBuildConfigurationModelProjectToBuildComAmcbridgeJenkinsPluginsModelsProjectToBuildModelArtifacts() {
        return new NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Artifacts();
    }

    /**
     * Create an instance of {@link NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.VersionFiles }
     * 
     */
    public NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.VersionFiles createComAmcbridgeJenkinsPluginsModelsBuildConfigurationModelProjectToBuildComAmcbridgeJenkinsPluginsModelsProjectToBuildModelVersionFiles() {
        return new NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.VersionFiles();
    }

    /**
     * Create an instance of {@link NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders.ComAmcbridgeJenkinsPluginsModelsBuilderConfigModel.Configs }
     * 
     */
    public NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders.ComAmcbridgeJenkinsPluginsModelsBuilderConfigModel.Configs createComAmcbridgeJenkinsPluginsModelsBuildConfigurationModelProjectToBuildComAmcbridgeJenkinsPluginsModelsProjectToBuildModelBuildersComAmcbridgeJenkinsPluginsModelsBuilderConfigModelConfigs() {
        return new NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders.ComAmcbridgeJenkinsPluginsModelsBuilderConfigModel.Configs();
    }

}
