//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.16 at 03:17:18 PM EET 
//


package model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An OldObjectFactory allows you to programatically
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class OldObjectFactory {


    /**
     * Create a new OldObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public OldObjectFactory() {
    }

    /**
     * Create an instance of {@link OldBuildConfigurationModel }
     * 
     */
    public OldBuildConfigurationModel createComAmcbridgeJenkinsPluginsModelsBuildConfigurationModel() {
        return new OldBuildConfigurationModel();
    }

    /**
     * Create an instance of {@link OldBuildConfigurationModel.UserWithAccess }
     * 
     */
    public OldBuildConfigurationModel.UserWithAccess createComAmcbridgeJenkinsPluginsModelsBuildConfigurationModelUserWithAccess() {
        return new OldBuildConfigurationModel.UserWithAccess();
    }

    /**
     * Create an instance of {@link OldBuildConfigurationModel.ProjectToBuild }
     * 
     */
    public OldBuildConfigurationModel.ProjectToBuild createComAmcbridgeJenkinsPluginsModelsBuildConfigurationModelProjectToBuild() {
        return new OldBuildConfigurationModel.ProjectToBuild();
    }

    /**
     * Create an instance of {@link OldBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel }
     * 
     */
    public OldBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel createComAmcbridgeJenkinsPluginsModelsBuildConfigurationModelProjectToBuildComAmcbridgeJenkinsPluginsModelsProjectToBuildModel() {
        return new OldBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel();
    }

    /**
     * Create an instance of {@link OldBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders }
     * 
     */
    public OldBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders createComAmcbridgeJenkinsPluginsModelsBuildConfigurationModelProjectToBuildComAmcbridgeJenkinsPluginsModelsProjectToBuildModelBuilders() {
        return new OldBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders();
    }

    /**
     * Create an instance of {@link OldBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders.ComAmcbridgeJenkinsPluginsModelsBuilderConfigModel }
     * 
     */
    public OldBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders.ComAmcbridgeJenkinsPluginsModelsBuilderConfigModel createComAmcbridgeJenkinsPluginsModelsBuildConfigurationModelProjectToBuildComAmcbridgeJenkinsPluginsModelsProjectToBuildModelBuildersComAmcbridgeJenkinsPluginsModelsBuilderConfigModel() {
        return new OldBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders.ComAmcbridgeJenkinsPluginsModelsBuilderConfigModel();
    }

    /**
     * Create an instance of {@link OldBuildConfigurationModel.BuildMachineConfiguration }
     * 
     */
    public OldBuildConfigurationModel.BuildMachineConfiguration createComAmcbridgeJenkinsPluginsModelsBuildConfigurationModelBuildMachineConfiguration() {
        return new OldBuildConfigurationModel.BuildMachineConfiguration();
    }

    /**
     * Create an instance of {@link OldBuildConfigurationModel.UserWithAccess.ComAmcbridgeJenkinsPluginsModelsUserAccessModel }
     * 
     */
    public OldBuildConfigurationModel.UserWithAccess.ComAmcbridgeJenkinsPluginsModelsUserAccessModel createComAmcbridgeJenkinsPluginsModelsBuildConfigurationModelUserWithAccessComAmcbridgeJenkinsPluginsModelsUserAccessModel() {
        return new OldBuildConfigurationModel.UserWithAccess.ComAmcbridgeJenkinsPluginsModelsUserAccessModel();
    }

    /**
     * Create an instance of {@link OldBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Artefacts }
     * 
     */
    public OldBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Artefacts createComAmcbridgeJenkinsPluginsModelsBuildConfigurationModelProjectToBuildComAmcbridgeJenkinsPluginsModelsProjectToBuildModelArtefacts() {
        return new OldBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Artefacts();
    }

    /**
     * Create an instance of {@link OldBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.VersionFiles }
     * 
     */
    public OldBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.VersionFiles createComAmcbridgeJenkinsPluginsModelsBuildConfigurationModelProjectToBuildComAmcbridgeJenkinsPluginsModelsProjectToBuildModelVersionFiles() {
        return new OldBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.VersionFiles();
    }

    /**
     * Create an instance of {@link OldBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders.ComAmcbridgeJenkinsPluginsModelsBuilderConfigModel.Configs }
     * 
     */
    public OldBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders.ComAmcbridgeJenkinsPluginsModelsBuilderConfigModel.Configs createComAmcbridgeJenkinsPluginsModelsBuildConfigurationModelProjectToBuildComAmcbridgeJenkinsPluginsModelsProjectToBuildModelBuildersComAmcbridgeJenkinsPluginsModelsBuilderConfigModelConfigs() {
        return new OldBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders.ComAmcbridgeJenkinsPluginsModelsBuilderConfigModel.Configs();
    }

}
