//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.18 at 01:47:31 PM EET 
//


package model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="projectName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="creator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rejectionReason" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="scm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="configEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="scriptType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="preScript" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="postScript" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isJobUpdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="projectToBuild">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="com.amcbridge.jenkins.plugins.models.ProjectToBuildModel" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="projectUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="fileToBuild" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="localDirectoryPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="branchName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="credentials" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="isVersionFiles" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="builders">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="com.amcbridge.jenkins.plugins.models.BuilderConfigModel" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="builder" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="platform" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="userConfig" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="configs">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="com.amcbridge.jenkins.plugins.enums.Configuration" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                                 &lt;element name="builderArgs" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="guid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="artifacts">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="string" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="versionFiles">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="string" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="guid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="buildMachineConfiguration">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="entry" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="string" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="boolean" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="comments" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userWithAccess">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="com.amcbridge.jenkins.plugins.models.UserAccessModel" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="cleanWorkspace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="regExp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pollSCMTrigger" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="buildPeriodicallyTrigger" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="buildOnCommitTrigger" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="plugin" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "projectName",
    "email",
    "creator",
    "date",
    "rejectionReason",
    "scm",
    "configEmail",
    "scriptType",
    "preScript",
    "postScript",
    "isJobUpdate",
    "state",
    "projectToBuild",
    "buildMachineConfiguration",
    "comments",
    "userWithAccess",
    "cleanWorkspace",
    "regExp",
    "pollSCMTrigger",
    "buildPeriodicallyTrigger",
    "buildOnCommitTrigger"
})
@XmlRootElement(name = "com.amcbridge.jenkins.plugins.models.BuildConfigurationModel")
public class NewBuildConfigurationModel {

    @XmlElement(required = true)
    protected String projectName;
    @XmlElement(required = true)
    protected String email;
    @XmlElement(required = true)
    protected String creator;
    @XmlElement(required = true)
    protected String date;
    @XmlElement(required = true)
    protected String rejectionReason;
    @XmlElement(required = true)
    protected String scm;
    @XmlElement(required = true)
    protected String configEmail;
    @XmlElement(required = true)
    protected String scriptType;
    @XmlElement(required = true)
    protected String preScript;
    @XmlElement(required = true)
    protected String postScript;
    @XmlElement(required = true)
    protected String isJobUpdate;
    @XmlElement(required = true)
    protected String state;
    @XmlElement(required = true)
    protected NewBuildConfigurationModel.ProjectToBuild projectToBuild;
    @XmlElement(required = true)
    protected NewBuildConfigurationModel.BuildMachineConfiguration buildMachineConfiguration;
    @XmlElement(required = true)
    protected String comments;
    @XmlElement(required = true)
    protected NewBuildConfigurationModel.UserWithAccess userWithAccess;
    @XmlElement(required = true)
    protected String cleanWorkspace;
    @XmlElement(required = true)
    protected String regExp;
    @XmlElement(required = true)
    protected String pollSCMTrigger;
    @XmlElement(required = true)
    protected String buildPeriodicallyTrigger;
    @XmlElement(required = true)
    protected String buildOnCommitTrigger;
    @XmlAttribute(name = "plugin")
    protected String plugin;

    /**
     * Gets the value of the projectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * Sets the value of the projectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectName(String value) {
        this.projectName = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the creator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreator() {
        return creator;
    }

    /**
     * Sets the value of the creator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreator(String value) {
        this.creator = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the rejectionReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRejectionReason() {
        return rejectionReason;
    }

    /**
     * Sets the value of the rejectionReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRejectionReason(String value) {
        this.rejectionReason = value;
    }

    /**
     * Gets the value of the scm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScm() {
        return scm;
    }

    /**
     * Sets the value of the scm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScm(String value) {
        this.scm = value;
    }

    /**
     * Gets the value of the configEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigEmail() {
        return configEmail;
    }

    /**
     * Sets the value of the configEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigEmail(String value) {
        this.configEmail = value;
    }

    /**
     * Gets the value of the scriptType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScriptType() {
        return scriptType;
    }

    /**
     * Sets the value of the scriptType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScriptType(String value) {
        this.scriptType = value;
    }

    /**
     * Gets the value of the preScript property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreScript() {
        return preScript;
    }

    /**
     * Sets the value of the preScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreScript(String value) {
        this.preScript = value;
    }

    /**
     * Gets the value of the postScript property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostScript() {
        return postScript;
    }

    /**
     * Sets the value of the postScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostScript(String value) {
        this.postScript = value;
    }

    /**
     * Gets the value of the isJobUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsJobUpdate() {
        return isJobUpdate;
    }

    /**
     * Sets the value of the isJobUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsJobUpdate(String value) {
        this.isJobUpdate = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the projectToBuild property.
     * 
     * @return
     *     possible object is
     *     {@link NewBuildConfigurationModel.ProjectToBuild }
     *     
     */
    public NewBuildConfigurationModel.ProjectToBuild getProjectToBuild() {
        return projectToBuild;
    }

    /**
     * Sets the value of the projectToBuild property.
     * 
     * @param value
     *     allowed object is
     *     {@link NewBuildConfigurationModel.ProjectToBuild }
     *     
     */
    public void setProjectToBuild(NewBuildConfigurationModel.ProjectToBuild value) {
        this.projectToBuild = value;
    }

    /**
     * Gets the value of the buildMachineConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link NewBuildConfigurationModel.BuildMachineConfiguration }
     *     
     */
    public NewBuildConfigurationModel.BuildMachineConfiguration getBuildMachineConfiguration() {
        return buildMachineConfiguration;
    }

    /**
     * Sets the value of the buildMachineConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link NewBuildConfigurationModel.BuildMachineConfiguration }
     *     
     */
    public void setBuildMachineConfiguration(NewBuildConfigurationModel.BuildMachineConfiguration value) {
        this.buildMachineConfiguration = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the userWithAccess property.
     * 
     * @return
     *     possible object is
     *     {@link NewBuildConfigurationModel.UserWithAccess }
     *     
     */
    public NewBuildConfigurationModel.UserWithAccess getUserWithAccess() {
        return userWithAccess;
    }

    /**
     * Sets the value of the userWithAccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link NewBuildConfigurationModel.UserWithAccess }
     *     
     */
    public void setUserWithAccess(NewBuildConfigurationModel.UserWithAccess value) {
        this.userWithAccess = value;
    }

    /**
     * Gets the value of the cleanWorkspace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCleanWorkspace() {
        return cleanWorkspace;
    }

    /**
     * Sets the value of the cleanWorkspace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCleanWorkspace(String value) {
        this.cleanWorkspace = value;
    }

    /**
     * Gets the value of the regExp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegExp() {
        return regExp;
    }

    /**
     * Sets the value of the regExp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegExp(String value) {
        this.regExp = value;
    }

    /**
     * Gets the value of the pollSCMTrigger property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPollSCMTrigger() {
        return pollSCMTrigger;
    }

    /**
     * Sets the value of the pollSCMTrigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPollSCMTrigger(String value) {
        this.pollSCMTrigger = value;
    }

    /**
     * Gets the value of the buildPeriodicallyTrigger property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuildPeriodicallyTrigger() {
        return buildPeriodicallyTrigger;
    }

    /**
     * Sets the value of the buildPeriodicallyTrigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuildPeriodicallyTrigger(String value) {
        this.buildPeriodicallyTrigger = value;
    }

    /**
     * Gets the value of the buildOnCommitTrigger property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuildOnCommitTrigger() {
        return buildOnCommitTrigger;
    }

    /**
     * Sets the value of the buildOnCommitTrigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuildOnCommitTrigger(String value) {
        this.buildOnCommitTrigger = value;
    }

    /**
     * Gets the value of the plugin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlugin() {
        return plugin;
    }

    /**
     * Sets the value of the plugin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlugin(String value) {
        this.plugin = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="entry" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="string" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="boolean" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entry"
    })
    public static class BuildMachineConfiguration {

        protected List<NewBuildConfigurationModel.BuildMachineConfiguration.Entry> entry;

        /**
         * Gets the value of the entry property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the entry property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEntry().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link NewBuildConfigurationModel.BuildMachineConfiguration.Entry }
         * 
         * 
         */
        public List<NewBuildConfigurationModel.BuildMachineConfiguration.Entry> getEntry() {
            if (entry == null) {
                entry = new ArrayList<NewBuildConfigurationModel.BuildMachineConfiguration.Entry>();
            }
            return this.entry;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="string" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="boolean" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "string",
            "_boolean"
        })
        public static class Entry {

            @XmlElement(required = true)
            protected String string;
            @XmlElement(name = "boolean", required = true)
            protected String _boolean;

            /**
             * Gets the value of the string property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getString() {
                return string;
            }

            /**
             * Sets the value of the string property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setString(String value) {
                this.string = value;
            }

            /**
             * Gets the value of the boolean property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBoolean() {
                return _boolean;
            }

            /**
             * Sets the value of the boolean property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBoolean(String value) {
                this._boolean = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="com.amcbridge.jenkins.plugins.models.ProjectToBuildModel" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="projectUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="fileToBuild" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="localDirectoryPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="branchName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="credentials" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="isVersionFiles" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="builders">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="com.amcbridge.jenkins.plugins.models.BuilderConfigModel" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="builder" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="platform" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="userConfig" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="configs">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="com.amcbridge.jenkins.plugins.enums.Configuration" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                       &lt;element name="builderArgs" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="guid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="artifacts">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="string" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="versionFiles">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="string" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="guid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "comAmcbridgeJenkinsPluginsModelsProjectToBuildModel"
    })
    public static class ProjectToBuild {

        @XmlElement(name = "com.amcbridge.jenkins.plugins.models.ProjectToBuildModel")
        protected List<NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel> comAmcbridgeJenkinsPluginsModelsProjectToBuildModel;

        /**
         * Gets the value of the comAmcbridgeJenkinsPluginsModelsProjectToBuildModel property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the comAmcbridgeJenkinsPluginsModelsProjectToBuildModel property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getComAmcbridgeJenkinsPluginsModelsProjectToBuildModel().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel }
         * 
         * 
         */
        public List<NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel> getComAmcbridgeJenkinsPluginsModelsProjectToBuildModel() {
            if (comAmcbridgeJenkinsPluginsModelsProjectToBuildModel == null) {
                comAmcbridgeJenkinsPluginsModelsProjectToBuildModel = new ArrayList<NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel>();
            }
            return this.comAmcbridgeJenkinsPluginsModelsProjectToBuildModel;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="projectUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="fileToBuild" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="localDirectoryPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="branchName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="credentials" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="isVersionFiles" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="builders">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="com.amcbridge.jenkins.plugins.models.BuilderConfigModel" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="builder" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="platform" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="userConfig" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="configs">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="com.amcbridge.jenkins.plugins.enums.Configuration" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                             &lt;element name="builderArgs" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="guid" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="artifacts">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="string" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="versionFiles">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="string" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="guid" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "projectUrl",
            "fileToBuild",
            "localDirectoryPath",
            "branchName",
            "credentials",
            "isVersionFiles",
            "builders",
            "artifacts",
            "versionFiles",
            "guid"
        })
        public static class ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel {

            @XmlElement(required = true)
            protected String projectUrl;
            @XmlElement(required = true)
            protected String fileToBuild;
            @XmlElement(required = true)
            protected String localDirectoryPath;
            @XmlElement(required = true)
            protected String branchName;
            @XmlElement(required = true)
            protected String credentials;
            @XmlElement(required = true)
            protected String isVersionFiles;
            @XmlElement(required = true)
            protected NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders builders;
            @XmlElement(required = true)
            protected NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Artifacts artifacts;
            @XmlElement(required = true)
            protected NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.VersionFiles versionFiles;
            @XmlElement(required = true)
            protected String guid;

            /**
             * Gets the value of the projectUrl property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProjectUrl() {
                return projectUrl;
            }

            /**
             * Sets the value of the projectUrl property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProjectUrl(String value) {
                this.projectUrl = value;
            }

            /**
             * Gets the value of the fileToBuild property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFileToBuild() {
                return fileToBuild;
            }

            /**
             * Sets the value of the fileToBuild property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFileToBuild(String value) {
                this.fileToBuild = value;
            }

            /**
             * Gets the value of the localDirectoryPath property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLocalDirectoryPath() {
                return localDirectoryPath;
            }

            /**
             * Sets the value of the localDirectoryPath property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLocalDirectoryPath(String value) {
                this.localDirectoryPath = value;
            }

            /**
             * Gets the value of the branchName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBranchName() {
                return branchName;
            }

            /**
             * Sets the value of the branchName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBranchName(String value) {
                this.branchName = value;
            }

            /**
             * Gets the value of the credentials property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCredentials() {
                return credentials;
            }

            /**
             * Sets the value of the credentials property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCredentials(String value) {
                this.credentials = value;
            }

            /**
             * Gets the value of the isVersionFiles property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIsVersionFiles() {
                return isVersionFiles;
            }

            /**
             * Sets the value of the isVersionFiles property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIsVersionFiles(String value) {
                this.isVersionFiles = value;
            }

            /**
             * Gets the value of the builders property.
             * 
             * @return
             *     possible object is
             *     {@link NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders }
             *     
             */
            public NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders getBuilders() {
                return builders;
            }

            /**
             * Sets the value of the builders property.
             * 
             * @param value
             *     allowed object is
             *     {@link NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders }
             *     
             */
            public void setBuilders(NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders value) {
                this.builders = value;
            }

            /**
             * Gets the value of the artifacts property.
             * 
             * @return
             *     possible object is
             *     {@link NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Artifacts }
             *     
             */
            public NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Artifacts getArtifacts() {
                return artifacts;
            }

            /**
             * Sets the value of the artifacts property.
             * 
             * @param value
             *     allowed object is
             *     {@link NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Artifacts }
             *     
             */
            public void setArtifacts(NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Artifacts value) {
                this.artifacts = value;
            }

            /**
             * Gets the value of the versionFiles property.
             * 
             * @return
             *     possible object is
             *     {@link NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.VersionFiles }
             *     
             */
            public NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.VersionFiles getVersionFiles() {
                return versionFiles;
            }

            /**
             * Sets the value of the versionFiles property.
             * 
             * @param value
             *     allowed object is
             *     {@link NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.VersionFiles }
             *     
             */
            public void setVersionFiles(NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.VersionFiles value) {
                this.versionFiles = value;
            }

            /**
             * Gets the value of the guid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGuid() {
                return guid;
            }

            /**
             * Sets the value of the guid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGuid(String value) {
                this.guid = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="string" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "string"
            })
            public static class Artifacts {

                protected List<String> string;

                /**
                 * Gets the value of the string property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the string property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getString().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getString() {
                    if (string == null) {
                        string = new ArrayList<String>();
                    }
                    return this.string;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="com.amcbridge.jenkins.plugins.models.BuilderConfigModel" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="builder" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="platform" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="userConfig" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="configs">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="com.amcbridge.jenkins.plugins.enums.Configuration" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                   &lt;element name="builderArgs" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="guid" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "comAmcbridgeJenkinsPluginsModelsBuilderConfigModel"
            })
            public static class Builders {

                @XmlElement(name = "com.amcbridge.jenkins.plugins.models.BuilderConfigModel")
                protected List<NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders.ComAmcbridgeJenkinsPluginsModelsBuilderConfigModel> comAmcbridgeJenkinsPluginsModelsBuilderConfigModel;

                /**
                 * Gets the value of the comAmcbridgeJenkinsPluginsModelsBuilderConfigModel property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the comAmcbridgeJenkinsPluginsModelsBuilderConfigModel property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getComAmcbridgeJenkinsPluginsModelsBuilderConfigModel().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders.ComAmcbridgeJenkinsPluginsModelsBuilderConfigModel }
                 * 
                 * 
                 */
                public List<NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders.ComAmcbridgeJenkinsPluginsModelsBuilderConfigModel> getComAmcbridgeJenkinsPluginsModelsBuilderConfigModel() {
                    if (comAmcbridgeJenkinsPluginsModelsBuilderConfigModel == null) {
                        comAmcbridgeJenkinsPluginsModelsBuilderConfigModel = new ArrayList<NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders.ComAmcbridgeJenkinsPluginsModelsBuilderConfigModel>();
                    }
                    return this.comAmcbridgeJenkinsPluginsModelsBuilderConfigModel;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="builder" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="platform" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="userConfig" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="configs">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="com.amcbridge.jenkins.plugins.enums.Configuration" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *         &lt;element name="builderArgs" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="guid" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "builder",
                    "platform",
                    "userConfig",
                    "configs",
                    "builderArgs",
                    "guid"
                })
                public static class ComAmcbridgeJenkinsPluginsModelsBuilderConfigModel {

                    @XmlElement(required = true)
                    protected String builder;
                    @XmlElement(required = true)
                    protected String platform;
                    @XmlElement(required = true)
                    protected String userConfig;
                    @XmlElement(required = true)
                    protected NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders.ComAmcbridgeJenkinsPluginsModelsBuilderConfigModel.Configs configs;
                    @XmlElement(required = true)
                    protected String builderArgs;
                    @XmlElement(required = true)
                    protected String guid;

                    /**
                     * Gets the value of the builder property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getBuilder() {
                        return builder;
                    }

                    /**
                     * Sets the value of the builder property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setBuilder(String value) {
                        this.builder = value;
                    }

                    /**
                     * Gets the value of the platform property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getPlatform() {
                        return platform;
                    }

                    /**
                     * Sets the value of the platform property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setPlatform(String value) {
                        this.platform = value;
                    }

                    /**
                     * Gets the value of the userConfig property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getUserConfig() {
                        return userConfig;
                    }

                    /**
                     * Sets the value of the userConfig property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setUserConfig(String value) {
                        this.userConfig = value;
                    }

                    /**
                     * Gets the value of the configs property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders.ComAmcbridgeJenkinsPluginsModelsBuilderConfigModel.Configs }
                     *     
                     */
                    public NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders.ComAmcbridgeJenkinsPluginsModelsBuilderConfigModel.Configs getConfigs() {
                        return configs;
                    }

                    /**
                     * Sets the value of the configs property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders.ComAmcbridgeJenkinsPluginsModelsBuilderConfigModel.Configs }
                     *     
                     */
                    public void setConfigs(NewBuildConfigurationModel.ProjectToBuild.ComAmcbridgeJenkinsPluginsModelsProjectToBuildModel.Builders.ComAmcbridgeJenkinsPluginsModelsBuilderConfigModel.Configs value) {
                        this.configs = value;
                    }

                    /**
                     * Gets the value of the builderArgs property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getBuilderArgs() {
                        return builderArgs;
                    }

                    /**
                     * Sets the value of the builderArgs property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setBuilderArgs(String value) {
                        this.builderArgs = value;
                    }

                    /**
                     * Gets the value of the guid property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getGuid() {
                        return guid;
                    }

                    /**
                     * Sets the value of the guid property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setGuid(String value) {
                        this.guid = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="com.amcbridge.jenkins.plugins.enums.Configuration" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "comAmcbridgeJenkinsPluginsEnumsConfiguration"
                    })
                    public static class Configs {

                        @XmlElement(name = "com.amcbridge.jenkins.plugins.enums.Configuration")
                        protected List<String> comAmcbridgeJenkinsPluginsEnumsConfiguration;

                        /**
                         * Gets the value of the comAmcbridgeJenkinsPluginsEnumsConfiguration property.
                         * 
                         * <p>
                         * This accessor method returns a reference to the live list,
                         * not a snapshot. Therefore any modification you make to the
                         * returned list will be present inside the JAXB object.
                         * This is why there is not a <CODE>set</CODE> method for the comAmcbridgeJenkinsPluginsEnumsConfiguration property.
                         * 
                         * <p>
                         * For example, to add a new item, do as follows:
                         * <pre>
                         *    getComAmcbridgeJenkinsPluginsEnumsConfiguration().add(newItem);
                         * </pre>
                         * 
                         * 
                         * <p>
                         * Objects of the following type(s) are allowed in the list
                         * {@link String }
                         * 
                         * 
                         */
                        public List<String> getComAmcbridgeJenkinsPluginsEnumsConfiguration() {
                            if (comAmcbridgeJenkinsPluginsEnumsConfiguration == null) {
                                comAmcbridgeJenkinsPluginsEnumsConfiguration = new ArrayList<String>();
                            }
                            return this.comAmcbridgeJenkinsPluginsEnumsConfiguration;
                        }

                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="string" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "string"
            })
            public static class VersionFiles {

                protected List<String> string;

                /**
                 * Gets the value of the string property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the string property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getString().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getString() {
                    if (string == null) {
                        string = new ArrayList<String>();
                    }
                    return this.string;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="com.amcbridge.jenkins.plugins.models.UserAccessModel" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "comAmcbridgeJenkinsPluginsModelsUserAccessModel"
    })
    public static class UserWithAccess {

        @XmlElement(name = "com.amcbridge.jenkins.plugins.models.UserAccessModel")
        protected List<NewBuildConfigurationModel.UserWithAccess.ComAmcbridgeJenkinsPluginsModelsUserAccessModel> comAmcbridgeJenkinsPluginsModelsUserAccessModel;

        /**
         * Gets the value of the comAmcbridgeJenkinsPluginsModelsUserAccessModel property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the comAmcbridgeJenkinsPluginsModelsUserAccessModel property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getComAmcbridgeJenkinsPluginsModelsUserAccessModel().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link NewBuildConfigurationModel.UserWithAccess.ComAmcbridgeJenkinsPluginsModelsUserAccessModel }
         * 
         * 
         */
        public List<NewBuildConfigurationModel.UserWithAccess.ComAmcbridgeJenkinsPluginsModelsUserAccessModel> getComAmcbridgeJenkinsPluginsModelsUserAccessModel() {
            if (comAmcbridgeJenkinsPluginsModelsUserAccessModel == null) {
                comAmcbridgeJenkinsPluginsModelsUserAccessModel = new ArrayList<NewBuildConfigurationModel.UserWithAccess.ComAmcbridgeJenkinsPluginsModelsUserAccessModel>();
            }
            return this.comAmcbridgeJenkinsPluginsModelsUserAccessModel;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "userName"
        })
        public static class ComAmcbridgeJenkinsPluginsModelsUserAccessModel {

            @XmlElement(required = true)
            protected String userName;

            /**
             * Gets the value of the userName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUserName() {
                return userName;
            }

            /**
             * Sets the value of the userName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUserName(String value) {
                this.userName = value;
            }

        }

    }

}
